company: 'Axis Communications'
co: 'Axis'
position: 'Electronics Design Engineer'
Hiring Staff: 'Hiring Staff'
advert: 'Glassdoor'  ## not used

programme: 'Embedded Electronics Engineering'
university1: 'Lund University'
university2: 'University of Botswana'  ## not used
