company: 'microTECH Global Limited'
co: 'microTECH'
position: 'Graduate Design Engineer'
Hiring Staff: 'Hiring Staff'
advert: 'Glassdoor'  ## not used

Current Date: '2024 / Jul / 9'
company address: 'Thames Valley - Wiltshire'
Hiring Manager's Name: 'Hiring Staff'
City, State, Zip Code: 'United Kingdom'
reason: 'your innovative solutions in embedded systems and other hardware systems'

programme: 'Embedded Electronics Engineering'
university1: 'Lund University'
university2: 'University of Botswana'  ## not used
